# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  android: circleci/android@2.0.3
  
workflows:
  example-workflow:
    jobs:
      - android/build:
          executor: build 
