name: Android CI

on:
  push:
    tags:
      - qa.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Slack Notification Start
        uses: rtCamp/action-slack-notify@v2
        if: always()
        env:
          SLACK_ICON_EMOJI: ":ssm:"
          SLACK_TITLE: ":android: 빌드 시작 / 버전 : $($) / 브랜치 : $"
          SLACK_USERNAME: "ssm-mobile-builder-bot"
          SLACK_CHANNEL: "#github_actions_test"
          SLACK_COLOR: "#CCCCCC"
          SLACK_MESSAGE: "commit : $"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Slack Notification Finish With Success
        uses: rtCamp/action-slack-notify@v2
        if: success()
        env:
          SLACK_ICON_EMOJI: ":android2:"
          SLACK_TITLE: ":android2: 빌드 성공 / 버전 : $($) / 브랜치 : $"
          SLACK_USERNAME: "ssm-mobile-builder-bot"
          SLACK_CHANNEL: "#github_actions_test"
          SLACK_COLOR: "#00BFA5"
          SLACK_MESSAGE: "commit : $\n<$/$/$|파일다운로드>, <$$/|브라우징>"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack Notification Finish With Fail
        uses: rtCamp/action-slack-notify@v2
        if: failure()
        env:
          SLACK_ICON_EMOJI: ":android2:"
          SLACK_TITLE: ":android2: 빌드 실패 / 버전 : $($) / 브랜치 : $"
          SLACK_USERNAME: "ssm-mobile-builder-bot"
          SLACK_CHANNEL: "#github_actions_test"
          SLACK_COLOR: "#FF5252"
          SLACK_MESSAGE: "commit : $"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Firebase App Distribution
      uses: hasretsariyer/firebase-app-distribution-github-action@v1
      with:
        app_id: ${{secrets.FIREBASE_APP_ID}}
        firebase_token: ${{secrets.FIREBASE_TOKEN}}
        app_file: app-release.apk
        tester_groups: maintainers

